# Generated by Django 2.2.4 on 2020-08-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
    ]
