# Generated by Django 2.2.4 on 2020-08-02 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200801_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha emision'),
        ),
    ]
