# Generated by Django 2.2.4 on 2020-08-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20200802_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha emision'),
        ),
    ]
