# Generated by Django 2.2.4 on 2020-08-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_venta_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Referencia',
            new_name='referencia',
        ),
    ]
