# Generated by Django 2.2.4 on 2020-08-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200801_2209'),
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referencia',
        ),
    ]
